version: '3'

services:
  service:
    build: service
    ports:
      - "8000:8000"
    volumes:
      - "./service:/app/service"


  client:
    build: client
    depends_on:
      - service
    ports:
      - "9000:80"

