# Generated by Django 5.1 on 2024-08-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_work', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
            },
        ),
        migrations.CreateModel(
            name='NuclearReactorConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=10)),
                ('project_site_boundaries', models.JSONField()),
                ('project_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('project_phase', models.CharField(choices=[('design', 'Design'), ('design review', 'Design Review'), ('design approval', 'Design Approval'), ('construction', 'Construction'), ('testing', 'Testing'), ('regulatory review', 'Regulatory Review'), ('operational', 'Operational')], default='design', max_length=25)),
                ('estimated_construction_start_date', models.DateTimeField(verbose_name='estimated construction start date')),
                ('construction_start_date', models.DateTimeField(verbose_name='construction start date')),
                ('estimated_construction_completion_date', models.DateTimeField(verbose_name='estimated construction completion date')),
                ('construction_completion_date', models.DateTimeField(verbose_name='construction completion date')),
                ('estimated_cost', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('total_expenses', models.FloatField(default=0.0)),
                ('notes', models.TextField()),
                ('contractors', models.ManyToManyField(related_name='projects', to='api.contractor')),
            ],
            options={
                'verbose_name': 'Nuclear Reactor Construction Project',
                'verbose_name_plural': 'Nuclear Reactor Construction Projects',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date_incurred', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='api.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='api.nuclearreactorconstructionproject')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
                'ordering': ['date_incurred'],
            },
        ),
    ]
