# Generated by Django 5.1 on 2024-08-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contractor_contact_person_contractor_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='name',
            new_name='company_name',
        ),
    ]
