# Generated by Django 5.1 on 2024-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_contractor_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='construction_completion_date',
            field=models.DateField(verbose_name='construction completion date'),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='construction_start_date',
            field=models.DateField(verbose_name='construction start date'),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='estimated_construction_completion_date',
            field=models.DateField(verbose_name='estimated construction completion date'),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='estimated_construction_start_date',
            field=models.DateField(verbose_name='estimated construction start date'),
        ),
    ]
