# Generated by Django 5.1 on 2024-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_expenditure_date_incurred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contact_person',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='field_of_work',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='budget',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='estimated_construction_start_date',
            field=models.DateField(verbose_name='estimated construction start date'),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='estimated_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='project_phase',
            field=models.CharField(choices=[('design', 'Design'), ('design review', 'Design Review'), ('design approval', 'Design Approval'), ('construction', 'Construction'), ('testing', 'Testing'), ('regulatory review', 'Regulatory Review'), ('operational', 'Operational')], default='design', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='project_site_boundaries',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='project_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='total_expenses',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
