# Generated by Django 5.1 on 2024-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contractor_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('materials', 'Materials'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
    ]
