# Generated by Django 5.1 on 2024-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_zip_nuclearreactorconstructionproject_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuclearreactorconstructionproject',
            name='power_rating_gw',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
