# Generated by Django 5.1 on 2024-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_nuclearreactorconstructionproject_power_rating_gw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='contractors',
            field=models.ManyToManyField(null=True, related_name='projects', to='api.contractor'),
        ),
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='estimated_construction_start_date',
            field=models.DateField(null=True, verbose_name='estimated construction start date'),
        ),
    ]
