# Generated by Django 5.1 on 2024-08-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_nuclearreactorconstructionproject_contractors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
