# Generated by Django 5.1 on 2024-08-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_nuclearreactorconstructionproject_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuclearreactorconstructionproject',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.contractor'),
        ),
    ]
