# Generated by Django 5.1 on 2024-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_nuclearreactorconstructionproject_contractors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
